allow_entities_without_labels: true
index: false
testmode: false
batch: true
safe_label: loose
batch_size: 100000000
relation_type_threshold: 0.95
represent_values_and_annotations_as_json:
  iris:
    - http://purl.obolibrary.org/obo/IAO_0000115
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym

neo_node_labelling:
  - classes:
      - CL:0000548
    label: Animal_cell
  - classes:
      - UBERON:0010000
      - UBERON:0000178
    label: Multicellular_anatomical_structure
  - classes:
      - NCBITaxon:33208
    label: Metazoan
  - classes:
      - NCBITaxon:40674
    label: Mammalia
  - classes:
      - NCBITaxon:7215
      - FBbt:10000000
    label: Drosophila
  - classes:
      - NCBITaxon:8353
    label: Xenopus
  - classes:
      - NCBITaxon:6239
    label: Caenorhabditis_elegans
  - classes:
      - NCBITaxon:7227
    label: Drosophila_melanogaster
  - classes:
      - NCBITaxon:7955
    label: Danio_rerio
  - classes:
      - NCBITaxon:9606
    label: Homo_sapiens
  - classes:
      - HANCESTRO:0004
    label: Race
  - classes:
      - MONDO:0000001
    label: Disease
  - classes:
      - UBERON:0000105
      - FBdv:00007012
      - WBls:0000075
      - ZFS:0100000
      - MmusDv:0000000
      - HsapDv:0000000
      - XAO:1000000
    label: Developmental_stage
  - classes:
      - RO:0002131 some CL:0000010
      - CL:0000010
    label: cultured_cell
  - classes:
      - RO:0002131 some UBERON:0000002
      - UBERON:0000002
    label: uterine_cervix
  - classes:
      - RO:0002131 some UBERON:0000004
      - UBERON:0000004
    label: nose
  - classes:
      - RO:0002131 some UBERON:0000007
      - UBERON:0000007
    label: pituitary_gland
  - classes:
      - RO:0002131 some UBERON:0000043
      - UBERON:0000043
    label: tendon
  - classes:
      - RO:0002131 some UBERON:0000056
      - UBERON:0000056
    label: ureter
  - classes:
      - RO:0002131 some UBERON:0000057
      - UBERON:0000057
    label: urethra
  - classes:
      - RO:0002131 some UBERON:0000059
      - UBERON:0000059
    label: large_intestine
  - classes:
      - RO:0002131 some UBERON:0000160
      - UBERON:0000160
    label: intestine
  - classes:
      - RO:0002131 some UBERON:0000165
      - UBERON:0000165
    label: mouth
  - classes:
      - RO:0002131 some UBERON:0000178
      - UBERON:0000178
    label: blood
  - classes:
      - RO:0002131 some UBERON:0000310
      - UBERON:0000310
    label: breast
  - classes:
      - RO:0002131 some UBERON:0000473
      - UBERON:0000473
    label: testis
  - classes:
      - RO:0002131 some UBERON:0000945
      - UBERON:0000945
    label: stomach
  - classes:
      - RO:0002131 some UBERON:0000948
      - UBERON:0000948
    label: heart
  - classes:
      - RO:0002131 some UBERON:0000955
      - UBERON:0000955
    label: brain
  - classes:
      - RO:0002131 some UBERON:0000970
      - UBERON:0000970
    label: eye
  - classes:
      - RO:0002131 some UBERON:0000982
      - UBERON:0000982
    label: skeletal_joint
  - classes:
      - RO:0002131 some UBERON:0000989
      - UBERON:0000989
    label: penis
  - classes:
      - RO:0002131 some UBERON:0000992
      - UBERON:0000992
    label: ovary
  - classes:
      - RO:0002131 some UBERON:0000995
      - UBERON:0000995
    label: uterus
  - classes:
      - RO:0002131 some UBERON:0000996
      - UBERON:0000996
    label: vagina
  - classes:
      - RO:0002131 some UBERON:0000997
      - UBERON:0000997
    label: mammalian_vulva
  - classes:
      - RO:0002131 some UBERON:0000998
      - UBERON:0000998
    label: seminal_vesicle
  - classes:
      - RO:0002131 some UBERON:0001000
      - UBERON:0001000
    label: vas_deferens
  - classes:
      - RO:0002131 some UBERON:0001013
      - UBERON:0001013
    label: adipose_tissue
  - classes:
      - RO:0002131 some UBERON:0001021
      - UBERON:0001021
    label: nerve
  - classes:
      - RO:0002131 some UBERON:0001043
      - UBERON:0001043
    label: esophagus
  - classes:
      - RO:0002131 some UBERON:0001044
      - UBERON:0001044
    label: saliva-secreting_gland
  - classes:
      - RO:0002131 some UBERON:0001052
      - UBERON:0001052
    label: rectum
  - classes:
      - RO:0002131 some UBERON:0001103
      - UBERON:0001103
    label: diaphragm
  - classes:
      - RO:0002131 some UBERON:0001132
      - UBERON:0001132
    label: parathyroid_gland
  - classes:
      - RO:0002131 some UBERON:0001134
      - UBERON:0001134
    label: skeletal_muscle_tissue
  - classes:
      - RO:0002131 some UBERON:0001154
      - UBERON:0001154
    label: vermiform_appendix
  - classes:
      - RO:0002131 some UBERON:0001245
      - UBERON:0001245
    label: anus
  - classes:
      - RO:0002131 some UBERON:0001264
      - UBERON:0001264
    label: pancreas
  - classes:
      - RO:0002131 some UBERON:0001300
      - UBERON:0001300
    label: scrotum
  - classes:
      - RO:0002131 some UBERON:0001474
      - UBERON:0001474
    label: bone_element
  - classes:
      - RO:0002131 some UBERON:0001637
      - UBERON:0001637
    label: artery
  - classes:
      - RO:0002131 some UBERON:0001638
      - UBERON:0001638
    label: vein
  - classes:
      - RO:0002131 some UBERON:0001690
      - UBERON:0001690
    label: ear
  - classes:
      - RO:0002131 some UBERON:0001705
      - UBERON:0001705
    label: nail
  - classes:
      - RO:0002131 some UBERON:0001723
      - UBERON:0001723
    label: tongue
  - classes:
      - RO:0002131 some UBERON:0001737
      - UBERON:0001737
    label: larynx
  - classes:
      - RO:0002131 some UBERON:0001898
      - UBERON:0001898
    label: hypothalamus
  - classes:
      - RO:0002131 some UBERON:0001905
      - UBERON:0001905
    label: pineal_body
  - classes:
      - RO:0002131 some UBERON:0001911
      - UBERON:0001911
    label: mammary_gland
  - classes:
      - RO:0002131 some UBERON:0001981
      - UBERON:0001981
    label: blood_vessel
  - classes:
      - RO:0002131 some UBERON:0001982
      - UBERON:0001982
    label: capillary
  - classes:
      - RO:0002131 some UBERON:0001987
      - UBERON:0001987
    label: placenta
  - classes:
      - RO:0002131 some UBERON:0002046
      - UBERON:0002046
    label: thyroid_gland
  - classes:
      - RO:0002131 some UBERON:0002048
      - UBERON:0002048
    label: lung
  - classes:
      - RO:0002131 some UBERON:0002073
      - UBERON:0002073
    label: hair_follicle
  - classes:
      - RO:0002131 some UBERON:0002095
      - UBERON:0002095
    label: mesentery
  - classes:
      - RO:0002131 some UBERON:0002097
      - UBERON:0002097
    label: skin_of_body
  - classes:
      - RO:0002131 some UBERON:0002106
      - UBERON:0002106
    label: spleen
  - classes:
      - RO:0002131 some UBERON:0002107
      - UBERON:0002107
    label: liver
  - classes:
      - RO:0002131 some UBERON:0002108
      - UBERON:0002108
    label: small_intestine
  - classes:
      - RO:0002131 some UBERON:0002110
      - UBERON:0002110
    label: gallbladder
  - classes:
      - RO:0002131 some UBERON:0002113
      - UBERON:0002113
    label: kidney
  - classes:
      - RO:0002131 some UBERON:0002240
      - UBERON:0002240
    label: spinal_cord
  - classes:
      - RO:0002131 some UBERON:0002366
      - UBERON:0002366
    label: bulbo-urethral_gland
  - classes:
      - RO:0002131 some UBERON:0002367
      - UBERON:0002367
    label: prostate_gland
  - classes:
      - RO:0002131 some UBERON:0002369
      - UBERON:0002369
    label: adrenal_gland
  - classes:
      - RO:0002131 some UBERON:0002370
      - UBERON:0002370
    label: thymus
  - classes:
      - RO:0002131 some UBERON:0002372
      - UBERON:0002372
    label: tonsil
  - classes:
      - RO:0002131 some UBERON:0002411
      - UBERON:0002411
    label: clitoris
  - classes:
      - RO:0002131 some UBERON:0002465
      - UBERON:0002465
    label: lymphoid_system
  - classes:
      - RO:0002131 some UBERON:0003126
      - UBERON:0003126
    label: trachea
  - classes:
      - RO:0002131 some UBERON:0003672
      - UBERON:0003672
    label: dentition
  - classes:
      - RO:0002131 some UBERON:0003889
      - UBERON:0003889
    label: fallopian_tube
  - classes:
      - RO:0002131 some UBERON:0005160
      - UBERON:0005160
    label: vestigial_structure
  - classes:
      - RO:0002131 some UBERON:0005169
      - UBERON:0005169
    label: interstitial_tissue
  - classes:
      - RO:0002131 some UBERON:0006562
      - UBERON:0006562
    label: pharynx
  - classes:
      - RO:0002131 some UBERON:0008846
      - UBERON:0008846
    label: skeletal_ligament
  - classes:
      - RO:0002131 some UBERON:0012168
      - UBERON:0012168
    label: umbilical_cord_blood
  - classes:
      - RO:0002131 some UBERON:0015143
      - UBERON:0015143
    label: mesenteric_fat_pad
  - classes:
      - RO:0002131 some UBERON:0018707
      - UBERON:0018707
    label: bladder_organ
  - classes:
      - RO:0002131 some UBERON:3011048
      - UBERON:3011048
    label: obsolete_genital_system
curie_map:
  CL: http://purl.obolibrary.org/obo/CL_
  BFO: http://purl.obolibrary.org/obo/BFO_
  UBERON: http://purl.obolibrary.org/obo/UBERON_
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  FBbt: http://purl.obolibrary.org/obo/FBbt_
  HANCESTRO: http://purl.obolibrary.org/obo/HANCESTRO_
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  FBdv: http://purl.obolibrary.org/obo/FBdv_
  WBls: http://purl.obolibrary.org/obo/WBls_
  ZFS: http://purl.obolibrary.org/obo/ZFS_
  MmusDv: http://purl.obolibrary.org/obo/MmusDv_
  HsapDv: http://purl.obolibrary.org/obo/HsapDv_
  XAO: http://purl.obolibrary.org/obo/XAO_
  GITHUB: https://github.com/
  GITHUBH: http://github.com/
  PMID: http://www.ncbi.nlm.nih.gov/pubmed/
  orcid: https://orcid.org/
  doi: https://doi.org/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ncbigene: http://www.ncbi.nlm.nih.gov/gene/
  cc: http://creativecommons.org/ns#
  pato_rel: http://purl.obolibrary.org/obo/pato#
  so_rel: http://purl.obolibrary.org/obo/so#
  ro_rel: http://www.obofoundry.org/ro/ro.owl#
  owl: http://www.w3.org/2002/07/owl#
  skos: http://www.w3.org/2004/02/skos/core#
  ensembl: http://identifiers.org/ensembl/
  RO: http://purl.obolibrary.org/obo/RO_
  n2o: http://n2o.neo/custom/
  ILX: http://uri.interlex.org/base/ilx_
  PR: http://purl.obolibrary.org/obo/PR_
  SO: http://purl.obolibrary.org/obo/SO_
  OBI: http://purl.obolibrary.org/obo/OBI_
  PCL: http://purl.obolibrary.org/obo/PCL_
  EFO: http://www.ebi.ac.uk/efo/EFO_
  PATO: http://purl.obolibrary.org/obo/PATO_


filters:
  solr:
    exclusion:
      iri_prefix:
        - http://virtualflybrain.org/reports/VFBc_
      neo4j_node_label:
        - Channel
