name: YAML schema validator
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main, development ]
    paths:
      - 'config/prod/neo4j2owl-config.yaml'

jobs:
  yaml-schema-validation:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Schema validation
      id: schema
      run: |
        python src/test_neo2owl_config.py
    - name: Prepare schema validator comment
      if: failure()
      run: |
        echo "config/prod/neo4j2owl-config.yaml file failed the schema validation check   " > comment.md; cat validation.report >> comment.md
    - name: install Yamale
      run: brew install yamale
    - name: Regex based DL validation
      id: validation
      run: |
        yamale -s schema.yaml config/prod/neo4j2owl-config.yaml | tee output
        tail -n +4 output > validation.report
        echo ::set-output name=report::$(cat output)
    - name: Prepare DL validator comment
      if: contains(steps.validation.outputs.report, 'Error')
      run: |
        echo "<details>   <summary> config/prod/neo4j2owl-config.yaml file failed the regex based DL validation check </summary>   " > comment.md; cat validation.report >> comment.md
        exit 1
    - name: Prepare success comment
      run: |
        echo "config/prod/neo4j2owl-config.yaml file passed validation check   " > comment.md
    - name: Post comment validator comment
      if: always()
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: NejcZdovc/comment-pr@v1.1.1
      with:
        file: "../../comment.md"
